[package]
name = "riot-wrappers"
version = "0.4.0"
authors = ["Christian M. Amsüss <ca@etonomy.org>"]
edition = "2018"

description = "Rust API wrappers for the RIOT operating system"
documentation = "https://docs.rs/riot-wrappers/"
repository = "https://gitlab.com/etonomy/riot-wrappers"
readme = "README.md"
keywords = ["riot", "riot-os", "iot", "bindings", "embedded-hal-impl"]
categories = ["api-bindings", "no-std"]
license = "LGPL-2.1"


[dependencies]
embedded-hal = { version = "0.2.2", features = ["unproven"] }
nb = "0.1.1"
riot-sys = "0.3.0"
crc = { version = "^1", default-features = false }
byteorder = { version="1", default-features = false }
num-traits = { version = "0.2", default-features = false }

coap-numbers = { version = "^0.1.0", optional = true, default-features = false }

# Disabled by default because it's not sure yet how stable they will be from riot-wrappers' side
coap-message = { version = "0.0.3", optional = true }
coap-handler = { git = "https://gitlab.com/chrysn/coap-handler/", optional = true }

embedded-nal = { version = "0.1.0", optional = true }

[build-dependencies]
shlex = "0.1.1"

[features]
default = ["set_panic_handler"]
set_panic_handler = []

with_coap_message = ["coap-message" ]
with_coap_handler = ["coap-handler", "coap-numbers", "with_coap_message"]
with_embedded_nal = ["embedded-nal"]
