[package]
name = "riot-wrappers"
version = "0.5.0"
authors = ["Christian M. Amsüss <ca@etonomy.org>"]
edition = "2018"

description = "Rust API wrappers for the RIOT operating system"
documentation = "https://rustdoc.etonomy.org/riot_wrappers/"
repository = "https://gitlab.com/etonomy/riot-wrappers"
readme = "README.md"
keywords = ["riot", "riot-os", "iot", "bindings", "embedded-hal-impl"]
categories = ["api-bindings", "no-std"]
license = "LGPL-2.1"


[dependencies]
embedded-hal = { version = "0.2.4", features = ["unproven"] }
nb = "0.1.1"
riot-sys = "0.3.1"
byteorder = { version="1", default-features = false }
num-traits = { version = "0.2", default-features = false }

# For bluetil
heapless = "^0.5"

# For nimble UUID parsing
# see https://github.com/KokaKiwi/rust-hex/pull/42
hex = { git = "https://github.com/Luro02/rust-hex", default_features = false }

coap-numbers = { version = "^0.1.0", optional = true, default-features = false }

# Originally disabled by default because they were not published yet; now
# disabled by default because their code is not annotated to depend on RIOT
# modules, and because this is probably the right thing anyway (pulling in
# dependencies when they are actually used by the application)
coap-message = { version = "0.1", optional = true }
coap-handler = { version = "0.0.1", optional = true }
embedded-nal = { version = "0.1.0", optional = true }

[build-dependencies]
shlex = "0.1.1"

[features]
default = ["set_panic_handler"]
set_panic_handler = []

with_coap_message = ["coap-message" ]
with_coap_handler = ["coap-handler", "coap-numbers", "with_coap_message"]
with_embedded_nal = ["embedded-nal"]
