[package]
name = "riot-wrappers"
version = "0.2.2"
authors = ["Christian M. Amsüss <ca@etonomy.org>"]

description = "Rust API wrappers for the RIOT operating system"
documentation = "https://docs.rs/riot-wrappers/"
repository = "https://gitlab.com/etonomy/riot-wrappers"
readme = "README.md"
keywords = ["riot", "riot-os", "iot", "bindings", "embedded-hal-impl"]
categories = ["api-bindings", "no-std"]
license = "LGPL-2.1"


[dependencies]
embedded-hal = { version = "0.2.2", features = ["unproven"] }
nb = "0.1.1"
riot-sys = "0.2.1"
crc = { version = "^1", default-features = false }
byteorder = { version="1", default-features = false }

# Disabled by default because jnet is not available on crates.io
# If you need the version of this library that has it available, us it from the repository.
jnet = { git = "https://github.com/chrysn-pull-requests/jnet", branch="optional-payload-marker", optional = true } # see https://github.com/japaric/jnet/pull/3

[build-dependencies]
shlex = "0.1.1"

[features]
default = ["set_panic_handler"]
set_panic_handler = []

# See jnet dependency
with_jnet = ["jnet"]
