[package]
name = "riot-wrappers"
version = "0.7.9"
authors = ["Christian M. Amsüss <ca@etonomy.org>"]
edition = "2018"

description = "Rust API wrappers for the RIOT operating system"
documentation = "https://rustdoc.etonomy.org/riot_wrappers/"
repository = "https://gitlab.com/etonomy/riot-wrappers"
readme = "README.md"
keywords = ["riot", "riot-os", "iot", "bindings", "embedded-hal-impl"]
categories = ["api-bindings", "no-std"]
# This is chosen to ease code migration between this and other implementations
# of embedded-hal. Beware that for any practical use, the LGPL terms of RIOT-OS
# still apply to resulting binary; this is visible to any Cargo based license
# checkers by the matching license set on the riot-sys crate.
license = "MIT OR Apache-2.0"


[dependencies]
embedded-hal = { version = "0.2.4", features = ["unproven"] }
nb = "0.1.1"
riot-sys = "^0.5"
byteorder = { version="1", default-features = false }
num-traits = { version = "0.2", default-features = false }
mutex-trait = "0.2"

# nightly is required to get everything const nicely
cstr_core = { version = "^0.2.4", default-features = false, features = [ "nightly" ] }

heapless = "^0.7"

# For nimble UUID parsing
# see https://github.com/KokaKiwi/rust-hex/pull/42
hex = { package = "hex-noalloc", version = "0.3.2-post1", default-features = false }

coap-numbers = { version = "^0.1.0", optional = true, default-features = false }

embedded-graphics = "0.6"

# Originally disabled by default because they were not published yet; now
# disabled by default because their code is not annotated to depend on RIOT
# modules, and because this is probably the right thing anyway (pulling in
# dependencies when they are actually used by the application)
coap-message = { version = "^0.2.0-alpha.0", optional = true }
coap-handler = { version = "^0.1.0-alpha.0", optional = true }
embedded-nal = { version = "0.6.0", optional = true }
embedded-nal-tcpextensions = { version = "0.1", optional = true }
pin-utils = "0.1"

[build-dependencies]
shlex = "0.1.1"

[features]
default = ["set_panic_handler", "panic_handler_format"]
set_panic_handler = []
# If present, the panic handler uses string formatting to produce an error
# message. Otherwise, it just writes a static panic message to stdout.
panic_handler_format = []

with_coap_message = ["coap-message" ]
with_coap_handler = ["coap-handler", "coap-numbers", "with_coap_message"]
with_embedded_nal = ["embedded-nal", "embedded-nal-tcpextensions"]

# See msg::v2 documentation. Enabling this exposes components not under semver
# guarantees.
with_msg_v2 = []
