name: rustfmt

on:
  pull_request:
    branches:
      - '*'

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run cargo-fmt
      run: cargo fmt --check
